### ISSUE TITLE
Piping to the scheduler without a Speaker instance

### ISSUE THREAD

**Issue by blakewenloe** [chrvadala/music-beat-detector#3]
Is there a way to chain `musicBeatDetector.getAnalyzer()` and `musicBeatScheduler.start()` without piping to a Speaker instance? For context: https://github.com/konsumer/tplink-lightbulb/issues/35

**Comment by chrvadala** [comment]
Yes, of course. You can use a writer stream like this:
```js
fs.createWriteStream('/dev/null')
```

**Comment by blakewenloe** [comment]
Perfect, this worked. Thank you!
